{
 "title": "IMDB AI PIPELINE",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Common",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Ollama Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(rate(llm_request_duration_seconds_sum[5m])) / sum(rate(llm_request_duration_seconds_count[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Summary Length",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(llm_summary_characters_sum[5m])) / sum(rate(llm_summary_characters_count[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Go Ingestion Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(movies_processed_total[1m])) by (status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Task Processing rate",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(ai_tasks_processed_total[1m])) by (status)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "[BENCHMARK] .NET vs Go Migration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Ingestion Throughput (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(movies_processed_total{status=\"success\"}[1m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Consumption (Working Set)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_working_set_bytes{job=\"worker-dotnet\"}",
     "legendFormat": "{{job}} - Working Set"
    },
    {
     "expr": "process_resident_memory_bytes{job=~\"worker-go|worker-dotnet\"}",
     "legendFormat": "{{job}} - Resident Set (RSS)"
    }
   ]
  },
  {
   "title": " Processing Latency Percentiles (P50, P95, P99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(message_processing_duration_seconds_bucket[1m])) by (le, job))",
     "legendFormat": "{{job}} - P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(message_processing_duration_seconds_bucket[1m])) by (le, job))",
     "legendFormat": "{{job}} - P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(message_processing_duration_seconds_bucket[1m])) by (le, job))",
     "legendFormat": "{{job}} - P99"
    }
   ]
  }
 ]
}